# Generated by Django 5.2.17 on 2026-08-09 20:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=100, verbose_name='Categoria')),
                ('icone_categoria', models.CharField(max_length=100, verbose_name='Ícone da Categoria')),
                ('pergunta', models.TextField(verbose_name='Pergunta')),
                ('instrucao', models.CharField(default='Escolha apenas uma opção.', max_length=150, verbose_name='Instrução')),
            ],
        ),
        migrations.CreateModel(
            name='Opcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(max_length=2, verbose_name='Chave (a, b, c...)')),
                ('icone', models.CharField(max_length=100, verbose_name='Ícone')),
                ('cor_icone', models.CharField(max_length=20, verbose_name='Cor do Ícone')),
                ('label', models.CharField(max_length=150, verbose_name='Label')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opcoes', to='accounts.pergunta', verbose_name='Pergunta')),
            ],
            options={
                'verbose_name': 'Opção',
                'verbose_name_plural': 'Opções',
                'unique_together': {('pergunta', 'chave')},
            },
        ),
        migrations.CreateModel(
            name='RespostaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('opcao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.opcao', verbose_name='Opção Selecionada')),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.pergunta', verbose_name='Pergunta')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Resposta de Usuário',
                'verbose_name_plural': 'Respostas de Usuários',
                'unique_together': {('user', 'pergunta')},
            },
        ),
    ]
