# Generated by Django 5.2.17 on 2026-08-09 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_pergunta_opcao_respostausuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Curso')),
                ('tipo', models.CharField(max_length=100, verbose_name='Tipo (e.g. Bacharelado, Tecnólogo)')),
                ('duracao', models.CharField(max_length=50, verbose_name='Duração (e.g. 4 anos)')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('area', models.CharField(choices=[('tecnologia', 'Tecnologia'), ('saude', 'Saúde'), ('negocios', 'Negócios')], default='tecnologia', max_length=20, verbose_name='Área do Curso')),
                ('tags_raw', models.CharField(max_length=500, verbose_name='Tags (separadas por vírgula)')),
                ('match_percent', models.IntegerField(default=85, verbose_name='Percentual de Match')),
                ('icone', models.CharField(default='school-outline', max_length=100, verbose_name='Ícone Ionicons')),
                ('cor_icone', models.CharField(default='#6B21A8', max_length=20, verbose_name='Cor do Ícone')),
                ('cor_fundo', models.CharField(default='#111827', max_length=20, verbose_name='Cor de Fundo da Caixa de Ícone')),
            ],
        ),
    ]
