# Generated by Django 5.2.17 on 2026-08-09 21:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_curso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Desafio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('xp', models.IntegerField(verbose_name='XP Bônus')),
                ('icone', models.CharField(max_length=100, verbose_name='Ícone Ionicons')),
                ('cor_icone', models.CharField(max_length=20, verbose_name='Cor do Ícone')),
                ('action_text', models.CharField(blank=True, max_length=100, null=True, verbose_name='Texto do Botão de Ação')),
                ('route_target', models.CharField(blank=True, max_length=100, null=True, verbose_name='Rota Alvo Interna')),
            ],
            options={
                'verbose_name': 'Desafio',
                'verbose_name_plural': 'Desafios',
            },
        ),
        migrations.CreateModel(
            name='DesafioConcluido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concluido_em', models.DateField(auto_now_add=True, verbose_name='Concluído Em')),
                ('desafio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.desafio', verbose_name='Desafio')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desafios_concluidos', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Desafio Concluído',
                'verbose_name_plural': 'Desafios Concluídos',
                'unique_together': {('user', 'desafio', 'concluido_em')},
            },
        ),
    ]
