# Generated by Django 5.2.17 on 2026-08-10 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_desafio_desafioconcluido'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='objetivo_carreira',
            field=models.CharField(blank=True, default='Tecnologia', max_length=150, null=True, verbose_name='Objetivo de Carreira'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='streak',
            field=models.IntegerField(default=1, verbose_name='Sequência de dias logado'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='ultimo_login_dia',
            field=models.DateField(blank=True, null=True, verbose_name='Último login no dia'),
        ),
    ]
