# Generated by Django 5.2.17 on 2026-08-10 00:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_objetivo_carreira_customuser_streak_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='area',
            field=models.CharField(choices=[('tecnologia', 'Tecnologia'), ('saude', 'Saúde'), ('negocios', 'Negócios'), ('artes', 'Artes'), ('direito', 'Direito'), ('agronomia', 'Agronomia')], default='tecnologia', max_length=30, verbose_name='Área do Curso'),
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logica', models.IntegerField(default=0, verbose_name='Lógica')),
                ('criatividade', models.IntegerField(default=0, verbose_name='Criatividade')),
                ('foco', models.IntegerField(default=0, verbose_name='Foco')),
                ('comunicacao', models.IntegerField(default=0, verbose_name='Comunicação')),
                ('lideranca', models.IntegerField(default=0, verbose_name='Liderança')),
                ('matematica', models.IntegerField(default=0, verbose_name='Matemática')),
                ('fisica', models.IntegerField(default=0, verbose_name='Física')),
                ('programacao', models.IntegerField(default=0, verbose_name='Programação')),
                ('desenho', models.IntegerField(default=0, verbose_name='Desenho')),
                ('portugues', models.IntegerField(default=0, verbose_name='Português')),
                ('biologia', models.IntegerField(default=0, verbose_name='Biologia')),
                ('quimica', models.IntegerField(default=0, verbose_name='Química')),
                ('historia', models.IntegerField(default=0, verbose_name='História')),
                ('tecnologia', models.IntegerField(default=0, verbose_name='Tecnologia')),
                ('saude', models.IntegerField(default=0, verbose_name='Saúde')),
                ('negocios', models.IntegerField(default=0, verbose_name='Negócios')),
                ('artes', models.IntegerField(default=0, verbose_name='Artes')),
                ('direito', models.IntegerField(default=0, verbose_name='Direito')),
                ('agronomia', models.IntegerField(default=0, verbose_name='Agronomia')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Perfil de Usuário',
                'verbose_name_plural': 'Perfis de Usuários',
            },
        ),
    ]
