# Generated by Django 5.2.17 on 2026-08-14 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_curso_area_perfilusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='opcao',
            name='peso',
            field=models.JSONField(blank=True, default=dict, verbose_name='Peso'),
        ),
        migrations.AlterField(
            model_name='opcao',
            name='cor_icone',
            field=models.CharField(default='#8B5CF6', max_length=20, verbose_name='Cor do Ícone'),
        ),
        migrations.AlterField(
            model_name='opcao',
            name='descricao',
            field=models.CharField(max_length=300, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='opcao',
            name='label',
            field=models.CharField(max_length=200, verbose_name='Rótulo'),
        ),
    ]
