# Generated by Django 5.2.17 on 2026-08-27 23:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_opcao_peso_alter_opcao_cor_icone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='embedding',
            field=models.JSONField(blank=True, null=True, verbose_name='Embedding da Descrição'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='free_text_daily_life',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Dia de Trabalho Ideal'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='free_text_dislikes',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='O que não deseja no trabalho'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='free_text_motivation',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Motivação Profissional'),
        ),
        migrations.CreateModel(
            name='CursoMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_final', models.IntegerField(default=0, verbose_name='Score Final')),
                ('score_tecnico', models.IntegerField(default=0, verbose_name='Score Técnico')),
                ('score_comportamental', models.IntegerField(default=0, verbose_name='Score Comportamental')),
                ('score_pragmatico', models.IntegerField(default=0, verbose_name='Score Pragmático')),
                ('sub_scores', models.JSONField(default=dict, verbose_name='Sub-scores Detalhados')),
                ('explicacao', models.TextField(blank=True, null=True, verbose_name='Explicabilidade da IA')),
                ('explicacao_status', models.CharField(choices=[('pending', 'Pendente'), ('completed', 'Concluído'), ('failed', 'Falhou')], default='pending', max_length=20, verbose_name='Status da Explicabilidade')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Calculado em')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_matches', to='accounts.curso', verbose_name='Curso')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curso_matches', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Match de Curso',
                'verbose_name_plural': 'Matches de Cursos',
                'unique_together': {('user', 'curso')},
            },
        ),
    ]
