version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: nexocareer_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: nexo_db
      POSTGRES_USER: nexo_user
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - nexocareer_postgres_data:/var/lib/postgresql/data
    networks:
      - nexocareer

  redis:
    image: redis:7-alpine
    container_name: nexocareer_redis
    restart: unless-stopped
    networks:
      - nexocareer

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nexocareer_backend
    restart: unless-stopped
    env_file:
      - .env
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    expose:
      - "8000"
    depends_on:
      - db
      - redis
    networks:
      - nexocareer
      - proxy

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nexocareer_celery
    restart: unless-stopped
    entrypoint: []
    env_file:
      - .env
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    command: celery -A config worker --loglevel=info
    depends_on:
      - db
      - redis
    networks:
      - nexocareer

volumes:
  nexocareer_postgres_data:

networks:
  nexocareer:
  proxy:
    external: true
